# CLI tools

brew "awscli"
brew "openssl"
brew "terraform"

# Casks

cask_args appdir: "/Applications"
cask "1password"
cask "docker"
cask "dropbox"
cask "evernote"
cask "google-chrome"
cask "pritunl"
cask "slack"
cask "spotify"
cask "sublime-text-3"
